name: Test Action
on:
  release:
    types: [published]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: yakubique/orogene@v0.3.25
        with:
          root: "./test-subject"
